import VueRouter from 'vue-router';

import language from '../i18n';
import Error404 from '../components/errors/404.vue';
import AppComponent from '../components/AppComponent.vue';
import ViewComponent from '../components/views/index.vue';
import SaleViewComponent from '../components/views/Sale.vue';
import LoginComponent from '../components/LoginComponent.vue';
import PaymentViewComponent from '../components/views/Payment.vue';
import SoonComponent from '../components/helpers/SoonComponent.vue';
import PurchaseViewComponent from '../components/views/Purchase.vue';
import DashboardComponent from '../components/DashboardComponent.vue';
import QuotationViewComponent from '../components/views/Quotation.vue';
import ReturnOrderViewComponent from '../components/views/ReturnOrder.vue';
import ParentRouteOutletComponent from '../components/ParentRouteOutletComponent.vue';

// const debug = process.env.NODE_ENV !== 'production';

function allRoutesFn(lang) {
  const i18n = language(lang);
  return [
    {
      path: '/',
      // name: 'home',
      component: AppComponent,
      meta: { title: 'App', icon: 'md-home' },
      children: [
        {
          path: '/',
          name: 'dashboard',
          component: DashboardComponent,
          meta: { title: i18n.t('dashboard'), icon: 'md-home' },
        },
        {
          name: 'calendar',
          path: '/calendar',
          // component: CalendarComponent,
          component: () => import(/* webpackChunkName: "utils" */ '../components/utilities/CalendarComponent.vue'),
          meta: { title: i18n.t('calendar'), icon: 'md-calendar', hideInMenu: true },
        },
        {
          name: 'orders',
          path: '/orders',
          component: ParentRouteOutletComponent,
          meta: { title: i18n.t('point_of_sale'), icon: 'ios-apps', mName: 'pos', permissions: ['pos-sales', 'read-orders'] },
          children: [
            {
              path: 'new',
              redirect: '/pos',
              name: 'pos.sale',
              meta: {
                super: true,
                mName: 'orders',
                icon: 'ios-apps',
                permission: 'pos-sales',
                title: i18n.t('point_of_sale'),
              },
            },
            {
              path: '/orders',
              name: 'orders.list',
              component: () => import(/* webpackChunkName: "sales" */ '../components/sales/OpenOrderListComponent.vue'),
              meta: {
                mName: 'orders',
                permission: 'read-orders',
                icon: 'ios-basket-outline',
                title: i18n.t('open') + ' ' + i18n.tc('order', 2),
              },
            },
          ],
        },
        {
          name: 'sales',
          path: '/sales',
          component: ParentRouteOutletComponent,
          meta: {
            mName: 'sales',
            icon: 'ios-basket',
            title: i18n.tc('sale', 2),
            permissions: [
              'read-sales',
              'create-sales',
              'import-sales',
              'read-deliveries',
              'read-recurring-sales',
              'create-recurring-sales',
            ],
          },
          children: [
            {
              path: '/sales',
              name: 'sales.list',
              component: () => import(/* webpackChunkName: "sales" */ '../components/sales/SaleListComponent.vue'),
              meta: { title: i18n.t('list_x', { x: i18n.tc('sale', 2) }), icon: 'ios-basket', mName: 'sales', permission: 'read-sales' },
            },
            {
              path: 'add',
              name: 'sales.add',
              component: () => import(/* webpackChunkName: "sales" */ '../components/sales/SaleFormComponent.vue'),
              meta: {
                mName: 'sales',
                icon: 'ios-basket-outline',
                permission: 'create-sales',
                title: i18n.t('add_x', { x: i18n.tc('sale') }),
              },
            },
            {
              path: 'edit/:id',
              name: 'sales.edit',
              component: () => import(/* webpackChunkName: "sales" */ '../components/sales/SaleFormComponent.vue'),
              meta: {
                mName: 'sales',
                hideInMenu: true,
                icon: 'ios-basket',
                permission: 'update-sales',
                title: i18n.t('edit_x', { x: i18n.tc('sale') }),
              },
            },
            {
              path: '/deliveries',
              name: 'deliveries.list',
              component: () => import(/* webpackChunkName: "sales" */ '../components/deliveries/DeliveryListComponent.vue'),
              meta: {
                mName: 'sales',
                icon: 'ios-bus',
                permission: 'read-deliveries',
                title: i18n.t('list_x', { x: i18n.tc('delivery', 2) }),
              },
            },
            {
              name: 'deliveries.add',
              path: '/deliveries/add',
              component: () => import(/* webpackChunkName: "sales" */ '../components/deliveries/DeliveryFormComponent.vue'),
              meta: {
                mName: 'sales',
                icon: 'ios-bus',
                hideInMenu: true,
                permission: 'create-deliveries',
                title: i18n.t('add_x', { x: i18n.tc('delivery') }),
              },
            },
            {
              name: 'deliveries.edit',
              path: '/deliveries/edit/:id',
              component: () => import(/* webpackChunkName: "sales" */ '../components/deliveries/DeliveryFormComponent.vue'),
              meta: {
                mName: 'sales',
                icon: 'ios-bus',
                hideInMenu: true,
                permission: 'update-deliveries',
                title: i18n.t('edit_x', { x: i18n.tc('delivery') }),
              },
            },
            {
              path: 'recurring',
              name: 'recurring_sales.list',
              component: () => import(/* webpackChunkName: "sales" */ '../components/sales/RecurringSaleListComponent.vue'),
              meta: {
                divided: true,
                mName: 'sales',
                icon: 'ios-basket',
                permission: 'read-recurring-sales',
                title: i18n.t('list_x', { x: i18n.tc('recurring_sale', 2) }),
              },
            },
            {
              path: 'recurring/add',
              name: 'recurring_sales.add',
              component: () => import(/* webpackChunkName: "sales" */ '../components/sales/RecurringSaleFormComponent.vue'),
              meta: {
                mName: 'sales',
                icon: 'ios-basket-outline',
                permission: 'create-recurring-sales',
                title: i18n.t('add_x', { x: i18n.tc('recurring_sale') }),
              },
            },
            {
              path: 'recurring/edit/:id',
              name: 'recurring_sales.edit',
              component: () => import(/* webpackChunkName: "sales" */ '../components/sales/RecurringSaleFormComponent.vue'),
              meta: {
                mName: 'sales',
                hideInMenu: true,
                icon: 'ios-basket',
                permission: 'update-recurring-sales',
                title: i18n.t('edit_x', { x: i18n.tc('recurring_sale') }),
              },
            },
            {
              path: 'import',
              name: 'sales.import',
              component: SoonComponent,
              // component: () => import(/* webpackChunkName: "sales" */ '../components/sales/SaleImportComponent.vue'),
              meta: {
                divided: true,
                mName: 'sales',
                hideInMenu: true,
                permission: 'import-sales',
                icon: 'ios-cloud-upload-outline',
                title: i18n.t('import_x', { x: i18n.tc('sale', 2) }),
              },
            },
          ],
        },
        {
          name: 'customers',
          path: '/customers',
          component: ParentRouteOutletComponent,
          meta: {
            icon: 'ios-people',
            mName: 'customers',
            title: i18n.tc('customer', 2),
            permissions: ['read-customers', 'create-customers', 'import-customers'],
          },
          children: [
            {
              path: '/customers',
              name: 'customers.list',
              component: () => import(/* webpackChunkName: "people" */ '../components/customers/CustomerListComponent.vue'),
              meta: {
                icon: 'ios-people',
                mName: 'customers',
                permission: 'read-customers',
                title: i18n.t('list_x', { x: i18n.tc('customer', 2) }),
              },
            },
            {
              path: 'add',
              name: 'customers.add',
              component: () => import(/* webpackChunkName: "people" */ '../components/customers/CustomerFormComponent.vue'),
              meta: {
                mName: 'customers',
                icon: 'ios-people-outline',
                permission: 'create-customers',
                title: i18n.t('add_x', { x: i18n.tc('customer') }),
              },
            },
            {
              path: 'edit/:id',
              name: 'customers.edit',
              component: () => import(/* webpackChunkName: "people" */ '../components/customers/CustomerFormComponent.vue'),
              meta: {
                hideInMenu: true,
                icon: 'ios-people',
                mName: 'customers',
                permission: 'update-customers',
                title: i18n.t('edit_x', { x: i18n.tc('customer') }),
              },
            },
            {
              path: 'import',
              name: 'customers.import',
              component: SoonComponent,
              // component: () => import(/* webpackChunkName: "people" */ '../components/customers/CustomerImportComponent.vue'),
              meta: {
                divided: true,
                hideInMenu: true,
                mName: 'customers',
                permission: 'import-customers',
                icon: 'ios-cloud-upload-outline',
                title: i18n.t('import_x', { x: i18n.tc('customer', 2) }),
              },
            },
            {
              path: 'transactions/:id',
              name: 'customers.transactions',
              component: () => import(/* webpackChunkName: "people" */ '../components/customers/TransactionsComponent.vue'),
              meta: {
                hideInMenu: true,
                mName: 'customers',
                permission: 'transactions-customers',
                title: i18n.t('list_x', { x: i18n.tc('customer') + ' ' + i18n.tc('transaction', 2) }),
              },
            },
          ],
        },
        {
          name: 'purchases',
          path: '/purchases',
          component: ParentRouteOutletComponent,
          meta: {
            icon: 'ios-cart',
            mName: 'purchases',
            title: i18n.tc('purchase', 2),
            permissions: ['read-purchases', 'create-purchases', 'import-purchases'],
          },
          children: [
            {
              name: 'purchases.list',
              path: '/purchases',
              component: () => import(/* webpackChunkName: "sales" */ '../components/purchases/PurchaseListComponent.vue'),
              meta: {
                icon: 'ios-cart',
                mName: 'purchases',
                permission: 'read-purchases',
                title: i18n.t('list_x', { x: i18n.tc('purchase', 2) }),
              },
            },
            {
              path: 'add',
              name: 'purchases.add',
              component: () => import(/* webpackChunkName: "sales" */ '../components/purchases/PurchaseFormComponent.vue'),
              meta: {
                mName: 'purchases',
                icon: 'ios-cart-outline',
                permission: 'create-purchases',
                title: i18n.t('add_x', { x: i18n.tc('purchase') }),
              },
            },
            {
              path: 'edit/:id',
              name: 'purchases.edit',
              component: () => import(/* webpackChunkName: "sales" */ '../components/purchases/PurchaseFormComponent.vue'),
              meta: {
                hideInMenu: true,
                icon: 'ios-cart',
                mName: 'purchases',
                permission: 'update-purchases',
                title: i18n.t('edit_x', { x: i18n.tc('purchase') }),
              },
            },
            {
              path: 'import',
              name: 'purchases.import',
              component: SoonComponent,
              // component: () => import(/* webpackChunkName: "sales" */ '../components/purchases/PurchaseImportComponent.vue'),
              meta: {
                divided: true,
                hideInMenu: true,
                mName: 'purchases',
                permission: 'import-purchases',
                icon: 'ios-cloud-upload-outline',
                title: i18n.t('import_x', { x: i18n.tc('purchase', 2) }),
              },
            },
          ],
        },
        {
          name: 'suppliers',
          path: '/suppliers',
          component: ParentRouteOutletComponent,
          meta: {
            mName: 'suppliers',
            icon: 'md-contacts',
            title: i18n.tc('supplier', 2),
            permissions: ['read-suppliers', 'create-suppliers', 'import-suppliers'],
          },
          children: [
            {
              path: '/suppliers',
              name: 'suppliers.list',
              component: () => import(/* webpackChunkName: "people" */ '../components/suppliers/SupplierListComponent.vue'),
              meta: {
                mName: 'suppliers',
                icon: 'md-contacts',
                permission: 'read-suppliers',
                title: i18n.t('list_x', { x: i18n.tc('supplier', 2) }),
              },
            },
            {
              path: 'add',
              name: 'suppliers.add',
              component: () => import(/* webpackChunkName: "people" */ '../components/suppliers/SupplierFormComponent.vue'),
              meta: {
                mName: 'suppliers',
                icon: 'md-contacts',
                permission: 'create-suppliers',
                title: i18n.t('add_x', { x: i18n.tc('supplier') }),
              },
            },
            {
              path: 'edit/:id',
              name: 'suppliers.edit',
              component: () => import(/* webpackChunkName: "people" */ '../components/suppliers/SupplierFormComponent.vue'),
              meta: {
                hideInMenu: true,
                mName: 'suppliers',
                icon: 'md-contacts',
                permission: 'update-suppliers',
                title: i18n.t('edit_x', { x: i18n.tc('supplier') }),
              },
            },
            {
              path: 'import',
              name: 'suppliers.import',
              component: SoonComponent,
              // component: () => import(/* webpackChunkName: "people" */ '../components/suppliers/SupplierImportComponent.vue'),
              meta: {
                divided: true,
                hideInMenu: true,
                mName: 'suppliers',
                permission: 'import-suppliers',
                icon: 'ios-cloud-upload-outline',
                title: i18n.t('import_x', { x: i18n.tc('supplier', 2) }),
              },
            },
            {
              path: 'transactions/:id',
              name: 'supplier.transactions',
              component: () => import(/* webpackChunkName: "people" */ '../components/suppliers/TransactionsComponent.vue'),
              meta: {
                hideInMenu: true,
                mName: 'supplier_transactions',
                permission: 'transactions-suppliers',
                title: i18n.t('list_x', { x: i18n.tc('supplier') + ' ' + i18n.tc('transaction', 2) }),
              },
            },
          ],
        },
        {
          name: 'quotations',
          path: '/quotations',
          component: ParentRouteOutletComponent,
          meta: {
            icon: 'ios-locate',
            mName: 'quotations',
            title: i18n.tc('quotation', 2),
            permissions: ['read-quotations', 'create-quotations'],
          },
          children: [
            {
              path: '/quotations',
              name: 'quotations.list',
              component: () => import(/* webpackChunkName: "sales" */ '../components/quotations/QuotationListComponent.vue'),
              meta: {
                icon: 'ios-locate',
                mName: 'quotations',
                permission: 'read-quotations',
                title: i18n.t('list_x', { x: i18n.tc('quotation', 2) }),
              },
            },
            {
              path: 'add',
              name: 'quotations.add',
              component: () => import(/* webpackChunkName: "sales" */ '../components/quotations/QuotationFormComponent.vue'),
              meta: {
                mName: 'quotations',
                icon: 'ios-locate-outline',
                permission: 'create-quotations',
                title: i18n.t('add_x', { x: i18n.tc('quotation') }),
              },
            },
            {
              path: 'edit/:id',
              name: 'quotations.edit',
              component: () => import(/* webpackChunkName: "sales" */ '../components/quotations/QuotationFormComponent.vue'),
              meta: {
                hideInMenu: true,
                icon: 'ios-locate',
                mName: 'quotations',
                permission: 'update-quotations',
                title: i18n.t('edit_x', { x: i18n.tc('quotation') }),
              },
            },
          ],
        },
        {
          name: 'return_orders',
          path: '/return_orders',
          component: ParentRouteOutletComponent,
          meta: {
            icon: 'ios-backspace',
            mName: 'return_orders',
            title: i18n.tc('return_order', 2),
            permissions: ['read-return-orders', 'create-return-orders'],
          },
          children: [
            {
              path: '/return_orders',
              name: 'return_orders.list',
              component: () => import(/* webpackChunkName: "sales" */ '../components/return_orders/ReturnOrderListComponent.vue'),
              meta: {
                icon: 'ios-backspace',
                mName: 'return_orders',
                permission: 'read-return-orders',
                title: i18n.t('list_x', { x: i18n.tc('return_order', 2) }),
              },
            },
            {
              path: 'add',
              name: 'return_orders.add',
              component: () => import(/* webpackChunkName: "sales" */ '../components/return_orders/ReturnOrderFormComponent.vue'),
              meta: {
                icon: 'ios-backspace-outline',
                mName: 'return_orders',
                permission: 'create-return-orders',
                title: i18n.t('add_x', { x: i18n.tc('return_order') }),
              },
            },
            {
              path: 'edit/:id',
              name: 'return_orders.edit',
              component: () => import(/* webpackChunkName: "sales" */ '../components/return_orders/ReturnOrderFormComponent.vue'),
              meta: {
                hideInMenu: true,
                icon: 'ios-backspace',
                mName: 'return_orders',
                permission: 'update-return-orders',
                title: i18n.t('edit_x', { x: i18n.tc('return_order') }),
              },
            },
          ],
        },
        {
          name: 'payments',
          path: '/payments',
          component: ParentRouteOutletComponent,
          meta: { title: i18n.tc('payment', 2), icon: 'ios-cash', mName: 'payments', permissions: ['read-payments', 'create-payments'] },
          children: [
            {
              path: '/payments',
              name: 'payments.list',
              component: () => import(/* webpackChunkName: "sales" */ '../components/payments/PaymentListComponent.vue'),
              meta: {
                icon: 'ios-cash',
                mName: 'payments',
                permission: 'read-payments',
                title: i18n.t('list_x', { x: i18n.tc('payment', 2) }),
              },
            },
            {
              path: 'add',
              name: 'payments.add',
              component: () => import(/* webpackChunkName: "sales" */ '../components/payments/PaymentFormComponent.vue'),
              meta: {
                mName: 'payments',
                icon: 'ios-cash-outline',
                permission: 'create-payments',
                title: i18n.t('add_x', { x: i18n.tc('payment') }),
              },
            },
            {
              path: 'edit/:id',
              name: 'payments.edit',
              component: () => import(/* webpackChunkName: "sales" */ '../components/payments/PaymentFormComponent.vue'),
              meta: {
                icon: 'ios-cash',
                hideInMenu: true,
                mName: 'payments',
                permission: 'update-payments',
                title: i18n.t('edit_x', { x: i18n.tc('payment') }),
              },
            },
          ],
        },
        {
          name: 'expenses',
          path: '/expenses',
          component: ParentRouteOutletComponent,
          meta: {
            icon: 'ios-flash',
            mName: 'expenses',
            title: i18n.tc('expense', 2),
            permissions: ['read-expenses', 'create-expenses', 'import-expenses'],
          },
          children: [
            {
              path: '/expenses',
              name: 'expenses.list',
              component: () => import(/* webpackChunkName: "utils" */ '../components/expenses/ExpenseListComponent.vue'),
              meta: {
                icon: 'ios-flash',
                mName: 'expenses',
                permission: 'read-expenses',
                title: i18n.t('list_x', { x: i18n.tc('expense', 2) }),
              },
            },
            {
              path: 'add',
              name: 'expenses.add',
              component: () => import(/* webpackChunkName: "utils" */ '../components/expenses/ExpenseFormComponent.vue'),
              meta: {
                mName: 'expenses',
                icon: 'ios-flash-outline',
                permission: 'create-expenses',
                title: i18n.t('add_x', { x: i18n.tc('expense') }),
              },
            },
            {
              path: 'edit/:id',
              name: 'expenses.edit',
              component: () => import(/* webpackChunkName: "utils" */ '../components/expenses/ExpenseFormComponent.vue'),
              meta: {
                hideInMenu: true,
                icon: 'ios-flash',
                mName: 'expenses',
                permission: 'update-expenses',
                title: i18n.t('edit_x', { x: i18n.tc('expense') }),
              },
            },
            {
              path: 'import',
              name: 'expenses.import',
              component: SoonComponent,
              // component: () => import(/* webpackChunkName: "utils" */ '../components/expenses/ExpenseImportComponent.vue'),
              meta: {
                divided: true,
                hideInMenu: true,
                mName: 'expenses',
                permission: 'import-expenses',
                icon: 'ios-cloud-upload-outline',
                title: i18n.t('import_x', { x: i18n.tc('expense', 2) }),
              },
            },
          ],
        },
        {
          name: 'incomes',
          path: '/incomes',
          component: ParentRouteOutletComponent,
          meta: {
            mName: 'incomes',
            icon: 'ios-flask',
            title: i18n.tc('income', 2),
            permissions: ['read-incomes', 'create-incomes', 'import-incomes'],
          },
          children: [
            {
              path: '/incomes',
              name: 'incomes.list',
              component: () => import(/* webpackChunkName: "utils" */ '../components/incomes/IncomeListComponent.vue'),
              meta: {
                title: i18n.t('list_x', { x: i18n.tc('income', 2) }),
                icon: 'ios-flask',
                mName: 'incomes',
                permission: 'read-incomes',
              },
            },
            {
              path: 'add',
              name: 'incomes.add',
              component: () => import(/* webpackChunkName: "utils" */ '../components/incomes/IncomeFormComponent.vue'),
              meta: {
                mName: 'incomes',
                icon: 'ios-flask-outline',
                permission: 'create-incomes',
                title: i18n.t('add_x', { x: i18n.tc('income') }),
              },
            },
            {
              path: 'edit/:id',
              name: 'incomes.edit',
              component: () => import(/* webpackChunkName: "utils" */ '../components/incomes/IncomeFormComponent.vue'),
              meta: {
                mName: 'incomes',
                hideInMenu: true,
                icon: 'ios-flask',
                permission: 'update-incomes',
                title: i18n.t('edit_x', { x: i18n.tc('income') }),
              },
            },
            {
              path: 'import',
              name: 'incomes.import',
              component: SoonComponent,
              // component: () => import(/* webpackChunkName: "utils" */ '../components/incomes/IncomeImportComponent.vue'),
              meta: {
                divided: true,
                hideInMenu: true,
                mName: 'incomes',
                permission: 'import-incomes',
                icon: 'ios-cloud-upload-outline',
                title: i18n.t('import_x', { x: i18n.tc('income', 2) }),
              },
            },
          ],
        },
        {
          name: 'items',
          path: '/items',
          component: ParentRouteOutletComponent,
          meta: {
            mName: 'items',
            icon: 'ios-tennisball',
            title: i18n.tc('item', 2),
            permissions: ['read-items', 'create-items', 'import-items', 'label-items'],
          },
          children: [
            {
              path: '/items',
              name: 'items.list',
              component: () => import(/* webpackChunkName: "utils" */ '../components/items/ItemListComponent.vue'),
              meta: {
                mName: 'items',
                icon: 'ios-tennisball',
                permission: 'read-items',
                title: i18n.t('list_x', { x: i18n.tc('item', 2) }),
              },
            },
            {
              path: 'add',
              name: 'items.add',
              component: () => import(/* webpackChunkName: "utils" */ '../components/items/ItemFormComponent.vue'),
              meta: {
                mName: 'items',
                permission: 'create-items',
                icon: 'ios-tennisball-outline',
                title: i18n.t('add_x', { x: i18n.tc('item') }),
              },
            },
            {
              path: 'edit/:id',
              name: 'items.edit',
              component: () => import(/* webpackChunkName: "utils" */ '../components/items/ItemFormComponent.vue'),
              meta: {
                mName: 'items',
                hideInMenu: true,
                icon: 'ios-tennisball',
                permission: 'update-items',
                title: i18n.t('edit_x', { x: i18n.tc('item') }),
              },
            },
            {
              path: '/items/services',
              name: 'items.services.list',
              component: () => import(/* webpackChunkName: "utils" */ '../components/items/ServiceListComponent.vue'),
              meta: {
                divided: true,
                mName: 'items',
                permission: 'read-items',
                icon: 'ios-color-palette',
                title: i18n.t('list_x', { x: i18n.tc('service', 2) }),
              },
            },
            {
              path: 'services/add',
              name: 'items.services.add',
              component: () => import(/* webpackChunkName: "utils" */ '../components/items/ServiceFormComponent.vue'),
              meta: {
                mName: 'items',
                permission: 'create-items',
                icon: 'ios-color-palette-outline',
                title: i18n.t('add_x', { x: i18n.tc('service') }),
              },
            },
            {
              path: 'services/edit/:id',
              name: 'items.services.edit',
              component: () => import(/* webpackChunkName: "utils" */ '../components/items/ServiceFormComponent.vue'),
              meta: {
                mName: 'items',
                hideInMenu: true,
                icon: 'ios-color-palette',
                permission: 'update-items',
                title: i18n.t('edit_x', { x: i18n.tc('item') }),
              },
            },
            {
              path: '/items/recipes',
              name: 'items.recipes.list',
              component: () => import(/* webpackChunkName: "utils" */ '../components/items/RecipeListComponent.vue'),
              meta: {
                divided: true,
                mName: 'items',
                restaurant: true,
                icon: 'ios-pizza',
                permission: 'read-items',
                title: i18n.t('list_x', { x: i18n.tc('recipe', 2) }),
              },
            },
            {
              path: 'recipes/add',
              name: 'items.recipes.add',
              component: () => import(/* webpackChunkName: "utils" */ '../components/items/RecipeFormComponent.vue'),
              meta: {
                mName: 'items',
                restaurant: true,
                icon: 'ios-pizza-outline',
                permission: 'create-items',
                title: i18n.t('add_x', { x: i18n.tc('recipe') }),
              },
            },
            {
              path: 'recipes/edit/:id',
              name: 'items.recipes.edit',
              component: () => import(/* webpackChunkName: "utils" */ '../components/items/RecipeFormComponent.vue'),
              meta: {
                mName: 'items',
                hideInMenu: true,
                icon: 'ios-pizza',
                permission: 'update-items',
                title: i18n.t('edit_x', { x: i18n.tc('item') }),
              },
            },
            {
              path: '/items/combos',
              name: 'items.combos.list',
              component: () => import(/* webpackChunkName: "utils" */ '../components/items/ComboListComponent.vue'),
              meta: {
                divided: true,
                mName: 'items',
                permission: 'read-items',
                icon: 'ios-color-filter',
                title: i18n.t('list_x', { x: i18n.tc('combo', 2) }),
              },
            },
            {
              path: 'combos/add',
              name: 'items.combos.add',
              component: () => import(/* webpackChunkName: "utils" */ '../components/items/ComboFormComponent.vue'),
              meta: {
                mName: 'items',
                permission: 'create-items',
                icon: 'ios-color-filter-outline',
                title: i18n.t('add_x', { x: i18n.tc('combo') }),
              },
            },
            {
              path: 'combos/edit/:id',
              name: 'items.combos.edit',
              component: () => import(/* webpackChunkName: "utils" */ '../components/items/ComboFormComponent.vue'),
              meta: {
                mName: 'items',
                hideInMenu: true,
                icon: 'ios-color-filter',
                permission: 'update-items',
                title: i18n.t('edit_x', { x: i18n.tc('item') }),
              },
            },
            {
              path: 'import',
              name: 'items.import',
              component: SoonComponent,
              // component: () => import(/* webpackChunkName: "utils" */ '../components/items/ItemFormComponent.vue'),
              meta: {
                divided: true,
                mName: 'items',
                hideInMenu: true,
                permission: 'import-items',
                icon: 'ios-cloud-upload-outline',
                title: i18n.t('import_x', { x: i18n.tc('item', 2) }),
              },
            },
            // {
            //   path: 'label',
            //   name: 'items.label',
            //   component: () => import(/* webpackChunkName: "utils" */ '../components/items/LabelComponent.vue'),
            //   meta: {
            //     divided: true,
            //     mName: 'items',
            //     hideInMenu: true,
            //     icon: 'ios-barcode',
            //     permission: 'label-items',
            //     title: i18n.t('item_label'),
            //   },
            // },
            {
              path: 'trails/:id',
              name: 'items.trails',
              // component: SoonComponent,
              component: () => import(/* webpackChunkName: "settings" */ '../components/items/ItemTrailComponent.vue'),
              meta: {
                divided: true,
                mName: 'items',
                hideInMenu: true,
                icon: 'md-analytics',
                permission: 'trail-items',
                title: i18n.t('item_trails'),
              },
            },
          ],
        },
        {
          name: 'modifiers',
          path: '/modifiers',
          component: ParentRouteOutletComponent,
          meta: {
            mName: 'modifiers',
            icon: 'ios-ice-cream',
            title: i18n.tc('modifier', 2),
            permissions: ['read-modifiers', 'create-modifiers', 'import-modifiers'],
          },
          children: [
            {
              path: '/modifiers',
              name: 'modifiers.list',
              component: () => import(/* webpackChunkName: "utils" */ '../components/modifiers/ModifierListComponent.vue'),
              meta: {
                mName: 'modifiers',
                icon: 'ios-ice-cream',
                permission: 'read-modifiers',
                title: i18n.t('list_x', { x: i18n.tc('modifier', 2) }),
              },
            },
            {
              path: 'add',
              name: 'modifiers.add',
              component: () => import(/* webpackChunkName: "utils" */ '../components/modifiers/ModifierFormComponent.vue'),
              meta: {
                mName: 'modifiers',
                icon: 'ios-ice-cream-outline',
                permission: 'create-modifiers',
                title: i18n.t('add_x', { x: i18n.tc('modifier') }),
              },
            },
            {
              path: 'edit/:id',
              name: 'modifiers.edit',
              component: () => import(/* webpackChunkName: "utils" */ '../components/modifiers/ModifierFormComponent.vue'),
              meta: {
                hideInMenu: true,
                mName: 'modifiers',
                icon: 'ios-ice-cream',
                permission: 'update-modifiers',
                title: i18n.t('edit_x', { x: i18n.tc('modifier') }),
              },
            },
            {
              path: 'import',
              name: 'modifiers.import',
              component: SoonComponent,
              // component: () => import(/* webpackChunkName: "utils" */ '../components/modifiers/ModifierFormComponent.vue'),
              meta: {
                divided: true,
                hideInMenu: true,
                mName: 'modifiers',
                permission: 'import-modifiers',
                icon: 'ios-cloud-upload-outline',
                title: i18n.t('import_x', { x: i18n.tc('modifier', 2) }),
              },
            },
          ],
        },
        {
          name: 'gift_cards',
          path: '/gift_cards',
          component: ParentRouteOutletComponent,
          meta: {
            icon: 'ios-card',
            title: i18n.tc('gift_card', 2),
            mName: 'gift_cards',
            permissions: ['read-gift-cards', 'create-gift-cards', 'log-gift-cards'],
          },
          children: [
            {
              path: '/gift_cards',
              name: 'gift_cards.list',
              component: () => import(/* webpackChunkName: "utils" */ '../components/gift_cards/GiftCardListComponent.vue'),
              meta: {
                icon: 'ios-card',
                mName: 'gift_cards',
                permission: 'read-gift-cards',
                title: i18n.t('list_x', { x: i18n.tc('gift_card', 2) }),
              },
            },
            {
              path: 'add',
              name: 'gift_cards.add',
              component: () => import(/* webpackChunkName: "utils" */ '../components/gift_cards/GiftCardFormComponent.vue'),
              meta: {
                mName: 'gift_cards',
                icon: 'ios-card-outline',
                permission: 'create-gift-cards',
                title: i18n.t('add_x', { x: i18n.tc('gift_card') }),
              },
            },
            {
              path: 'edit/:id',
              name: 'gift_cards.edit',
              component: () => import(/* webpackChunkName: "utils" */ '../components/gift_cards/GiftCardFormComponent.vue'),
              meta: {
                icon: 'ios-card',
                hideInMenu: true,
                mName: 'gift_cards',
                permission: 'update-gift-cards',
                title: i18n.t('edit_x', { x: i18n.tc('gift_card') }),
              },
            },
            {
              path: 'logs/:id',
              name: 'gift_cards.logs',
              component: () => import(/* webpackChunkName: "people" */ '../components/gift_cards/GiftCardLogsComponent.vue'),
              meta: {
                hideInMenu: true,
                mName: 'gift_cards',
                permission: 'log-gift-cards',
                title: i18n.tc('gift_card') + ' ' + i18n.tc('logs', 2),
              },
            },
          ],
        },
        {
          name: 'stock_adjustments',
          path: '/stock_adjustments',
          component: ParentRouteOutletComponent,
          meta: {
            icon: 'ios-options',
            mName: 'stock_adjustments',
            title: i18n.tc('stock_adjustment', 2),
            permissions: ['read-stock-adjustments', 'create-stock-adjustments'],
          },
          children: [
            {
              path: '/stock_adjustments',
              name: 'stock_adjustments.list',
              component: () => import(/* webpackChunkName: "utils" */ '../components/stock_adjustments/AdjustmentListComponent.vue'),
              meta: {
                icon: 'ios-options',
                mName: 'stock_adjustments',
                permission: 'read-stock-adjustments',
                title: i18n.t('list_x', { x: i18n.tc('stock_adjustment', 2) }),
              },
            },
            {
              path: 'add',
              name: 'stock_adjustments.add',
              component: () => import(/* webpackChunkName: "utils" */ '../components/stock_adjustments/AdjustmentFormComponent.vue'),
              meta: {
                mName: 'stock_adjustments',
                icon: 'ios-options-outline',
                permission: 'create-stock-adjustments',
                title: i18n.t('add_x', { x: i18n.tc('stock_adjustment') }),
              },
            },
            {
              path: 'edit/:id',
              name: 'stock_adjustments.edit',
              component: () => import(/* webpackChunkName: "utils" */ '../components/stock_adjustments/AdjustmentFormComponent.vue'),
              meta: {
                hideInMenu: true,
                icon: 'ios-options',
                mName: 'stock_adjustments',
                permission: 'update-stock-adjustments',
                title: i18n.t('edit_x', { x: i18n.tc('stock_adjustment') }),
              },
            },
          ],
        },
        {
          name: 'transfers',
          path: '/transfers',
          component: ParentRouteOutletComponent,
          meta: {
            mName: 'transfers',
            icon: 'ios-git-compare',
            title: i18n.tc('transfer', 2),
            permissions: ['read-asset-transfers', 'create-asset-transfers', 'read-stock-transfers', 'create-stock-transfers'],
          },
          children: [
            {
              path: '/transfers/asset',
              name: 'transfers.asset.list',
              component: () => import(/* webpackChunkName: "people" */ '../components/transfers/AssetListComponent.vue'),
              meta: {
                mName: 'transfers',
                icon: 'ios-git-pull-request',
                permission: 'read-asset-transfers',
                title: i18n.t('list_x', { x: i18n.tc('asset_transfer', 2) }),
              },
            },
            {
              path: 'asset/add',
              name: 'transfers.asset.add',
              component: () => import(/* webpackChunkName: "people" */ '../components/transfers/AssetFormComponent.vue'),
              meta: {
                mName: 'transfers',
                icon: 'ios-git-pull-request',
                permission: 'create-asset-transfers',
                title: i18n.t('add_x', { x: i18n.tc('asset_transfer') }),
              },
            },
            {
              path: 'asset/edit/:id',
              name: 'transfers.asset.edit',
              component: () => import(/* webpackChunkName: "people" */ '../components/transfers/AssetFormComponent.vue'),
              meta: {
                hideInMenu: true,
                mName: 'transfers',
                icon: 'ios-git-pull-request',
                permission: 'update-asset-transfers',
                title: i18n.t('edit_x', { x: i18n.tc('asset_transfer') }),
              },
            },
            {
              path: '/transfers/stock',
              name: 'transfers.stock.list',
              component: () => import(/* webpackChunkName: "people" */ '../components/transfers/StockListComponent.vue'),
              meta: {
                mName: 'transfers',
                icon: 'ios-git-compare',
                permission: 'read-stock-transfers',
                title: i18n.t('list_x', { x: i18n.tc('stock_transfer', 2) }),
              },
            },
            {
              path: 'stock/add',
              name: 'transfers.stock.add',
              component: () => import(/* webpackChunkName: "people" */ '../components/transfers/StockFormComponent.vue'),
              meta: {
                mName: 'transfers',
                icon: 'ios-git-compare',
                permission: 'create-stock-transfers',
                title: i18n.t('add_x', { x: i18n.tc('stock_transfer') }),
              },
            },
            {
              path: 'stock/edit/:id',
              name: 'transfers.stock.edit',
              component: () => import(/* webpackChunkName: "people" */ '../components/transfers/StockFormComponent.vue'),
              meta: {
                hideInMenu: true,
                mName: 'transfers',
                icon: 'ios-git-compare',
                permission: 'update-stock-transfers',
                title: i18n.t('edit_x', { x: i18n.tc('stock_transfer') }),
              },
            },
          ],
        },
        {
          name: 'users',
          path: '/users',
          component: ParentRouteOutletComponent,
          meta: {
            mName: 'users',
            access: 'super',
            icon: 'md-people',
            title: i18n.tc('user', 2),
            permissions: [
              'read-users',
              'create-users',
              'read-roles',
              'create-roles',
              'update-permissions',
              'read-salaries',
              'create-salaries',
            ],
          },
          children: [
            {
              path: '/users',
              name: 'users.list',
              component: () => import(/* webpackChunkName: "people" */ '../components/users/UserListComponent.vue'),
              meta: {
                mName: 'users',
                access: 'super',
                icon: 'md-people',
                permission: 'read-users',
                title: i18n.t('list_x', { x: i18n.tc('user', 2) }),
              },
            },
            {
              path: 'add',
              name: 'users.add',
              component: () => import(/* webpackChunkName: "people" */ '../components/users/UserFormComponent.vue'),
              meta: {
                mName: 'users',
                access: 'super',
                icon: 'md-people',
                permission: 'create-users',
                title: i18n.t('add_x', { x: i18n.tc('user') }),
              },
            },
            {
              path: 'edit/:id',
              name: 'users.edit',
              component: () => import(/* webpackChunkName: "people" */ '../components/users/UserFormComponent.vue'),
              meta: {
                mName: 'users',
                access: 'super',
                hideInMenu: true,
                icon: 'md-people',
                permission: 'update-users',
                title: i18n.t('edit_x', { x: i18n.tc('user') }),
              },
            },
            {
              path: 'roles',
              name: 'roles.list',
              component: () => import(/* webpackChunkName: "people" */ '../components/users/roles/RoleListComponent.vue'),
              meta: {
                mName: 'users',
                access: 'super',
                icon: 'ios-people',
                permission: 'read-roles',
                title: i18n.t('list_x', { x: i18n.tc('user_role', 2) }),
              },
            },
            {
              name: 'roles.add',
              path: 'roles/add',
              component: () => import(/* webpackChunkName: "people" */ '../components/users/roles/RoleFormComponent.vue'),
              meta: {
                mName: 'users',
                access: 'super',
                icon: 'ios-people',
                permission: 'create-roles',
                title: i18n.t('add_x', { x: i18n.tc('user_role') }),
              },
            },
            {
              name: 'roles.edit',
              path: 'roles/edit/:id',
              component: () => import(/* webpackChunkName: "people" */ '../components/users/roles/RoleFormComponent.vue'),
              meta: {
                mName: 'users',
                access: 'super',
                hideInMenu: true,
                icon: 'ios-people',
                permission: 'update-roles',
                title: i18n.t('edit_x', { x: i18n.tc('user_role') }),
              },
            },
            {
              name: 'roles.permissions',
              path: 'roles/:id/permissions',
              component: () => import(/* webpackChunkName: "people" */ '../components/users/roles/RolePermissionComponent.vue'),
              meta: {
                mName: 'users',
                access: 'super',
                hideInMenu: true,
                icon: 'md-options',
                permission: 'update-permissions',
                title: i18n.t('edit_x', { x: i18n.tc('permission', 2) }),
              },
            },
            {
              path: 'salaries',
              name: 'salaries.list',
              component: () => import(/* webpackChunkName: "people" */ '../components/users/salaries/SalaryListComponent.vue'),
              meta: {
                mName: 'users',
                access: 'super',
                icon: 'ios-people',
                permission: 'read-salaries',
                title: i18n.t('list_x', { x: i18n.tc('salary', 2) }),
              },
            },
            {
              name: 'salaries.add',
              path: 'salaries/add',
              component: () => import(/* webpackChunkName: "people" */ '../components/users/salaries/SalaryFormComponent.vue'),
              meta: {
                mName: 'users',
                access: 'super',
                icon: 'ios-people',
                permission: 'create-salaries',
                title: i18n.t('add_x', { x: i18n.tc('salary') }),
              },
            },
            {
              name: 'salaries.edit',
              path: 'salaries/edit/:id',
              component: () => import(/* webpackChunkName: "people" */ '../components/users/salaries/SalaryFormComponent.vue'),
              meta: {
                mName: 'users',
                access: 'super',
                hideInMenu: true,
                icon: 'ios-people',
                permission: 'update-salaries',
                title: i18n.t('edit_x', { x: i18n.tc('salary') }),
              },
            },
          ],
        },
        {
          name: 'profile',
          path: '/profile',
          component: () => import(/* webpackChunkName: "people" */ '../components/users/ProfileComponent.vue'),
          meta: { title: i18n.t('profile'), icon: 'md-user', hideInMenu: true },
        },
        {
          name: 'change_password',
          path: '/change_password',
          component: () => import(/* webpackChunkName: "people" */ '../components/users/ChangePasswordComponent.vue'),
          meta: { title: i18n.t('change_password'), icon: 'md-key', hideInMenu: true },
        },
        {
          path: 'settings',
          component: ParentRouteOutletComponent,
          meta: {
            title: i18n.tc('setting', 2),
            icon: 'ios-cog-outline',
            mName: 'settings',
            permissions: [
              'read-accounts',
              'create-accounts',
              'transactions-accounts',
              'read-locations',
              'create-locations',
              'read-promos',
              'create-promos',
              'read-brands',
              'create-brands',
              'read-categories',
              'create-categories',
              'read-taxes',
              'create-taxes',
              'read-fields',
              'create-fields',
              'read-customer-groups',
              'create-customer-groups',
              'read-halls',
              'create-halls',
              'read-tables',
              'create-tables',
              'read-units',
              'create-units',
            ],
          },
          children: [
            {
              name: 'settings',
              path: '/settings',
              component: () => import(/* webpackChunkName: "settings" */ '../components/settings/AppSettingsComponent.vue'),
              meta: { title: i18n.t('app_settings'), icon: 'ios-cog-outline', access: 'super', mName: 'settings' },
            },
            {
              name: 'settings.label',
              path: 'item-label-design',
              component: () => import(/* webpackChunkName: "settings" */ '../components/settings/LabelDesignComponent.vue'),
              meta: {
                divided: true,
                access: 'super',
                mName: 'settings',
                icon: 'ios-barcode',
                title: i18n.t('item_label_design'),
              },
            },
            {
              path: 'accounts',
              name: 'accounts.list',
              component: () => import(/* webpackChunkName: "settings" */ '../components/accounts/AccountListComponent.vue'),
              meta: {
                divided: true,
                access: 'super',
                icon: 'ios-book',
                mName: 'settings',
                title: i18n.t('list_x', { x: i18n.tc('account', 2) }),
              },
            },
            {
              name: 'accounts.add',
              path: 'accounts/add',
              component: () => import(/* webpackChunkName: "settings" */ '../components/accounts/AccountFormComponent.vue'),
              meta: {
                access: 'super',
                mName: 'settings',
                icon: 'ios-book-outline',
                title: i18n.t('add_x', { x: i18n.tc('account') }),
              },
            },
            {
              name: 'accounts.edit',
              path: 'accounts/edit/:id',
              component: () => import(/* webpackChunkName: "settings" */ '../components/accounts/AccountFormComponent.vue'),
              meta: {
                access: 'super',
                hideInMenu: true,
                icon: 'ios-book',
                mName: 'settings',
                title: i18n.t('edit_x', { x: i18n.tc('account') }),
              },
            },
            {
              name: 'accounts.transactions',
              path: 'accounts/transactions/:id',
              component: () => import(/* webpackChunkName: "settings" */ '../components/accounts/TransactionsComponent.vue'),
              meta: {
                access: 'super',
                hideInMenu: true,
                mName: 'account_transactions',
                title: i18n.t('list_x', { x: i18n.tc('account') + ' ' + i18n.tc('transaction', 2) }),
              },
            },
            {
              path: 'locations',
              name: 'locations.list',
              component: () => import(/* webpackChunkName: "settings" */ '../components/locations/LocationListComponent.vue'),
              meta: {
                access: 'super',
                divided: true,
                mName: 'settings',
                icon: 'ios-navigate',
                title: i18n.t('list_x', { x: i18n.tc('location', 2) }),
              },
            },
            {
              name: 'locations.add',
              path: 'locations/add',
              component: () => import(/* webpackChunkName: "settings" */ '../components/locations/LocationFormComponent.vue'),
              meta: {
                access: 'super',
                mName: 'settings',
                icon: 'ios-navigate-outline',
                title: i18n.t('add_x', { x: i18n.tc('location') }),
              },
            },
            {
              name: 'locations.edit',
              path: 'locations/edit/:id',
              component: () => import(/* webpackChunkName: "settings" */ '../components/locations/LocationFormComponent.vue'),
              meta: {
                access: 'super',
                hideInMenu: true,
                mName: 'settings',
                icon: 'ios-navigate',
                title: i18n.t('edit_x', { x: i18n.tc('location') }),
              },
            },
            {
              path: 'promos',
              name: 'promos.list',
              component: () => import(/* webpackChunkName: "settings" */ '../components/promos/PromoListComponent.vue'),
              meta: {
                divided: true,
                icon: 'ios-star',
                mName: 'settings',
                title: i18n.t('list_x', { x: i18n.tc('promo', 2) }),
              },
            },
            {
              name: 'promos.add',
              path: 'promos/add',
              component: () => import(/* webpackChunkName: "settings" */ '../components/promos/PromoFormComponent.vue'),
              meta: { title: i18n.t('add_x', { x: i18n.tc('promo') }), icon: 'ios-star-outline', mName: 'settings' },
            },
            {
              name: 'promos.edit',
              path: 'promos/edit/:id',
              component: () => import(/* webpackChunkName: "settings" */ '../components/promos/PromoFormComponent.vue'),
              meta: {
                icon: 'ios-star',
                hideInMenu: true,
                mName: 'settings',
                title: i18n.t('edit_x', { x: i18n.tc('promo') }),
              },
            },
            {
              path: 'brands',
              name: 'brands.list',
              component: () => import(/* webpackChunkName: "settings" */ '../components/brands/BrandListComponent.vue'),
              meta: {
                divided: true,
                mName: 'settings',
                icon: 'ios-pricetags',
                title: i18n.t('list_x', { x: i18n.tc('brand', 2) }),
              },
            },
            {
              name: 'brands.add',
              path: 'brands/add',
              component: () => import(/* webpackChunkName: "settings" */ '../components/brands/BrandFormComponent.vue'),
              meta: {
                mName: 'settings',
                icon: 'ios-pricetags-outline',
                title: i18n.t('add_x', { x: i18n.tc('brand') }),
              },
            },
            {
              name: 'brands.edit',
              path: 'brands/edit/:id',
              component: () => import(/* webpackChunkName: "settings" */ '../components/brands/BrandFormComponent.vue'),
              meta: {
                hideInMenu: true,
                mName: 'settings',
                icon: 'ios-pricetags',
                title: i18n.t('edit_x', { x: i18n.tc('brand') }),
              },
            },
            {
              path: 'categories',
              name: 'categories.list',
              component: () => import(/* webpackChunkName: "settings" */ '../components/categories/CategoryListComponent.vue'),
              meta: {
                divided: true,
                mName: 'settings',
                icon: 'ios-folder-open',
                title: i18n.t('list_x', { x: i18n.tc('category', 2) }),
              },
            },
            {
              name: 'categories.add',
              path: 'categories/add',
              component: () => import(/* webpackChunkName: "settings" */ '../components/categories/CategoryFormComponent.vue'),
              meta: {
                mName: 'settings',
                icon: 'ios-folder-open-outline',
                title: i18n.t('add_x', { x: i18n.tc('category') }),
              },
            },
            {
              name: 'categories.edit',
              path: 'categories/edit/:id',
              component: () => import(/* webpackChunkName: "settings" */ '../components/categories/CategoryFormComponent.vue'),
              meta: {
                hideInMenu: true,
                mName: 'settings',
                icon: 'ios-folder-open',
                title: i18n.t('edit_x', { x: i18n.tc('category') }),
              },
            },
            {
              path: 'taxes',
              name: 'taxes.list',
              component: () => import(/* webpackChunkName: "settings" */ '../components/taxes/TaxListComponent.vue'),
              meta: {
                divided: true,
                mName: 'settings',
                icon: 'ios-game-controller-a',
                title: i18n.t('list_x', { x: i18n.tc('tax', 2) }),
              },
            },
            {
              name: 'taxes.add',
              path: 'taxes/add',
              component: () => import(/* webpackChunkName: "settings" */ '../components/taxes/TaxFormComponent.vue'),
              meta: {
                mName: 'settings',
                icon: 'ios-game-controller-a-outline',
                title: i18n.t('add_x', { x: i18n.tc('tax') }),
              },
            },
            {
              name: 'taxes.edit',
              path: 'taxes/edit/:id',
              component: () => import(/* webpackChunkName: "settings" */ '../components/taxes/TaxFormComponent.vue'),
              meta: {
                hideInMenu: true,
                mName: 'settings',
                icon: 'ios-game-controller-a',
                title: i18n.t('edit_x', { x: i18n.tc('tax') }),
              },
            },
            {
              path: 'fields',
              name: 'fields.list',
              component: () => import(/* webpackChunkName: "settings" */ '../components/fields/FieldListComponent.vue'),
              meta: {
                divided: true,
                mName: 'settings',
                icon: 'ios-flower',
                title: i18n.t('list_x', { x: i18n.tc('field', 2) }),
              },
            },
            {
              name: 'fields.add',
              path: 'fields/add',
              component: () => import(/* webpackChunkName: "settings" */ '../components/fields/FieldFormComponent.vue'),
              meta: {
                mName: 'settings',
                icon: 'ios-flower-outline',
                title: i18n.t('add_x', { x: i18n.tc('field') }),
              },
            },
            {
              name: 'fields.edit',
              path: 'fields/edit/:id',
              component: () => import(/* webpackChunkName: "settings" */ '../components/fields/FieldFormComponent.vue'),
              meta: {
                hideInMenu: true,
                mName: 'settings',
                icon: 'ios-flower',
                title: i18n.t('edit_x', { x: i18n.tc('field') }),
              },
            },
            {
              path: 'customer_groups',
              name: 'customer_groups.list',
              component: () => import(/* webpackChunkName: "settings" */ '../components/customer_groups/CustomerGroupListComponent.vue'),
              meta: {
                divided: true,
                mName: 'settings',
                icon: 'ios-people',
                title: i18n.t('list_x', { x: i18n.tc('customer_group', 2) }),
              },
            },
            {
              name: 'customer_groups.add',
              path: 'customer_groups/add',
              component: () => import(/* webpackChunkName: "settings" */ '../components/customer_groups/CustomerGroupFormComponent.vue'),
              meta: {
                mName: 'settings',
                icon: 'ios-people-outline',
                title: i18n.t('add_x', { x: i18n.tc('customer_group') }),
              },
            },
            {
              name: 'customer_groups.edit',
              path: 'customer_groups/edit/:id',
              component: () => import(/* webpackChunkName: "settings" */ '../components/customer_groups/CustomerGroupFormComponent.vue'),
              meta: {
                hideInMenu: true,
                mName: 'settings',
                icon: 'ios-people',
                title: i18n.t('edit_x', { x: i18n.tc('customer_group') }),
              },
            },
            {
              path: 'halls',
              name: 'halls.list',
              component: () => import(/* webpackChunkName: "settings" */ '../components/halls/HallListComponent.vue'),
              meta: {
                divided: true,
                restaurant: true,
                mName: 'settings',
                icon: 'ios-square',
                title: i18n.t('list_x', { x: i18n.tc('hall', 2) }),
              },
            },
            {
              name: 'halls.add',
              path: 'halls/add',
              component: () => import(/* webpackChunkName: "settings" */ '../components/halls/HallFormComponent.vue'),
              meta: {
                restaurant: true,
                mName: 'settings',
                icon: 'ios-square-outline',
                title: i18n.t('add_x', { x: i18n.tc('hall') }),
              },
            },
            {
              name: 'halls.edit',
              path: 'halls/edit/:id',
              component: () => import(/* webpackChunkName: "settings" */ '../components/halls/HallFormComponent.vue'),
              meta: {
                hideInMenu: true,
                mName: 'settings',
                icon: 'ios-square',
                title: i18n.t('edit_x', { x: i18n.tc('hall') }),
              },
            },
            {
              path: 'halls/:hall_id/tables',
              name: 'tables.list',
              component: () => import(/* webpackChunkName: "settings" */ '../components/halls/HallTableListComponent.vue'),
              meta: {
                hideInMenu: true,
                mName: 'settings',
                icon: 'ios-square',
                title: i18n.t('list_x', { x: i18n.tc('table', 2) }),
              },
            },
            {
              name: 'tables.add',
              path: 'halls/:hall_id/tables/add',
              component: () => import(/* webpackChunkName: "settings" */ '../components/halls/HallTableFormComponent.vue'),
              meta: {
                hideInMenu: true,
                mName: 'settings',
                icon: 'ios-square-outline',
                title: i18n.t('add_x', { x: i18n.tc('table') }),
              },
            },
            {
              name: 'tables.edit',
              path: 'halls/:hall_id/tables/edit/:id',
              component: () => import(/* webpackChunkName: "settings" */ '../components/halls/HallTableFormComponent.vue'),
              meta: {
                hideInMenu: true,
                mName: 'settings',
                icon: 'ios-square',
                title: i18n.t('edit_x', { x: i18n.tc('table') }),
              },
            },
            {
              path: 'units',
              name: 'units.list',
              component: () => import(/* webpackChunkName: "settings" */ '../components/units/UnitListComponent.vue'),
              meta: {
                divided: true,
                mName: 'settings',
                icon: 'ios-pulse',
                title: i18n.t('list_x', { x: i18n.tc('uom', 2) }),
              },
            },
            {
              name: 'units.add',
              path: 'units/add',
              component: () => import(/* webpackChunkName: "settings" */ '../components/units/UnitFormComponent.vue'),
              meta: {
                mName: 'settings',
                icon: 'ios-pulse-outline',
                title: i18n.t('add_x', { x: i18n.tc('uom') }),
              },
            },
            {
              name: 'units.edit',
              path: 'units/edit/:id',
              component: () => import(/* webpackChunkName: "settings" */ '../components/units/UnitFormComponent.vue'),
              meta: {
                hideInMenu: true,
                mName: 'settings',
                icon: 'ios-pulse',
                title: i18n.t('edit_x', { x: i18n.tc('uom') }),
              },
            },
          ],
        },
        {
          path: 'reports',
          component: ParentRouteOutletComponent,
          meta: {
            title: i18n.tc('report', 2),
            icon: 'ios-podium',
            mName: 'reports',
            permissions: [
              'read-reports',
              'register-reports',
              'expiry-alert-reports',
              'quantity-alert-reports',
              'item-reports',
              'sale-reports',
              'purchase-reports',
              'payment-reports',
              'expense-reports',
              'income-reports',
              'stock-transfer-reports',
              'stock-adjustment-reports',
              'time-clock-reports',
              'activity-logs-reports',
            ],
          },
          children: [
            {
              path: '',
              name: 'reports',
              component: () => import(/* webpackChunkName: "reports" */ '../components/reports/ReportsComponent.vue'),
              meta: { title: i18n.tc('report', 2), icon: 'ios-pulse', mName: 'reports', permissions: 'read-reports' },
            },
            {
              path: 'registers',
              name: 'reports.registers',
              component: () => import(/* webpackChunkName: "reports" */ '../components/reports/RegisterRecordListComponent.vue'),
              meta: { title: i18n.tc('register', 2), icon: 'ios-briefcase', mName: 'reports', permissions: 'register-reports' },
            },
            {
              path: 'expiring',
              name: 'alerts.expiring',
              component: () => import(/* webpackChunkName: "reports" */ '../components/reports/ExpiryAlertComponent.vue'),
              meta: { title: i18n.t('expiry_alerts'), icon: 'md-alert', mName: 'reports', permissions: 'expiry-alert-reports' },
            },
            {
              path: 'quantity',
              name: 'alerts.quantity',
              component: () => import(/* webpackChunkName: "reports" */ '../components/reports/QuantityAlertComponent.vue'),
              meta: {
                title: i18n.t('quantity_alerts'),
                icon: 'ios-alert-outline',
                mName: 'reports',
                permissions: 'quantity-alert-reports',
              },
            },
            {
              path: 'items',
              name: 'reports.items',
              component: () => import(/* webpackChunkName: "reports" */ '../components/reports/ItemsReportComponent.vue'),
              meta: {
                mName: 'reports',
                icon: 'ios-tennisball',
                permissions: 'item-reports',
                title: i18n.t('x_report', { x: i18n.tc('item', 2) }),
              },
            },
            {
              path: 'items/top',
              name: 'reports.items.top',
              component: () => import(/* webpackChunkName: "reports" */ '../components/reports/TopItemsReportComponent.vue'),
              meta: {
                mName: 'reports',
                icon: 'md-thumbs-up',
                permissions: 'item-reports',
                title: i18n.t('x_report', { x: i18n.t('top_items') }),
              },
            },
            {
              path: 'sales',
              name: 'reports.sales',
              component: () => import(/* webpackChunkName: "reports" */ '../components/reports/SalesReportComponent.vue'),
              meta: {
                mName: 'reports',
                icon: 'ios-basket',
                permissions: 'sale-reports',
                title: i18n.t('x_report', { x: i18n.tc('sale', 2) }),
              },
            },
            {
              path: 'purchases',
              name: 'reports.purchases',
              component: () => import(/* webpackChunkName: "reports" */ '../components/reports/PurchasesReportComponent.vue'),
              meta: {
                icon: 'ios-cart',
                mName: 'reports',
                permissions: 'purchase-reports',
                title: i18n.t('x_report', { x: i18n.tc('purchase', 2) }),
              },
            },
            {
              path: 'payments',
              name: 'reports.payments',
              component: () => import(/* webpackChunkName: "reports" */ '../components/reports/PaymentsReportComponent.vue'),
              meta: {
                icon: 'ios-cash',
                mName: 'reports',
                permissions: 'payment-reports',
                title: i18n.t('x_report', { x: i18n.tc('payment', 2) }),
              },
            },
            {
              path: 'expenses',
              name: 'reports.expenses',
              component: () => import(/* webpackChunkName: "reports" */ '../components/reports/ExpensesReportComponent.vue'),
              meta: {
                mName: 'reports',
                icon: 'ios-cloud-upload',
                permissions: 'expense-reports',
                title: i18n.t('x_report', { x: i18n.tc('expense', 2) }),
              },
            },
            {
              path: 'incomes',
              name: 'reports.incomes',
              component: () => import(/* webpackChunkName: "reports" */ '../components/reports/IncomesReportComponent.vue'),
              meta: {
                mName: 'reports',
                icon: 'ios-flask',
                permissions: 'income-reports',
                title: i18n.t('x_report', { x: i18n.tc('income', 2) }),
              },
            },
            {
              path: 'tax',
              name: 'reports.tax',
              component: () => import(/* webpackChunkName: "reports" */ '../components/reports/TaxReportComponent.vue'),
              meta: {
                mName: 'reports',
                permissions: 'read-reports',
                icon: 'ios-game-controller-a',
                title: i18n.t('x_report', { x: i18n.tc('tax') }),
              },
            },
            {
              path: 'stock_transfers',
              name: 'reports.stock_transfers',
              component: () => import(/* webpackChunkName: "reports" */ '../components/reports/StockTransfersReportComponent.vue'),
              meta: {
                mName: 'reports',
                icon: 'ios-git-compare',
                title: i18n.tc('stock_transfer', 2),
                permissions: 'stock-transfer-reports',
              },
            },
            {
              path: 'stock_adjustments',
              name: 'reports.stock_adjustments',
              component: () => import(/* webpackChunkName: "reports" */ '../components/reports/StockAdjustmentsReportComponent.vue'),
              meta: {
                mName: 'reports',
                icon: 'ios-options',
                title: i18n.tc('stock_adjustment', 2),
                permissions: 'stock-adjustment-reports',
              },
            },
            {
              path: 'time_clock',
              name: 'reports.time_clock',
              component: () => import(/* webpackChunkName: "reports" */ '../components/reports/TimeClockListComponent.vue'),
              meta: { title: i18n.tc('time_clock', 2), icon: 'md-clock', mName: 'reports', permissions: 'time-clock-reports' },
            },
            {
              path: 'logs',
              name: 'reports.logs',
              component: () => import(/* webpackChunkName: "reports" */ '../components/reports/LogsComponent.vue'),
              meta: { title: i18n.t('activity_logs'), icon: 'ios-paper', mName: 'reports', permissions: 'activity-logs-reports' },
            },
          ],
        },
      ],
    },
    {
      name: 'pos',
      path: '/pos',
      component: () => import(/* webpackChunkName: "sales" */ '../components/pos/PosComponent.vue'),
      meta: { title: i18n.t('pos'), icon: 'md-apps', hideInMenu: true },
    },
    {
      name: 'customer_view',
      path: '/customer-view',
      component: () => import(/* webpackChunkName: "sales" */ '../components/pos/CustomerViewComponent.vue'),
      meta: { title: i18n.t('customer_view'), icon: 'ios-desktop', hideInMenu: true },
    },
    {
      name: 'login',
      path: '/login',
      component: LoginComponent,
      meta: { title: i18n.t('login'), icon: 'md-user', hideInMenu: true },
    },
    {
      name: 'login.force',
      path: '/login/force',
      component: LoginComponent,
      meta: { title: i18n.t('login'), icon: 'md-user', force: true, hideInMenu: true },
    },
    {
      name: 'views',
      path: '/views',
      component: ViewComponent,
      meta: { title: i18n.tc('sale'), hideInMenu: true },
    },
    {
      name: 'views.sale',
      path: '/views/sale/:hash',
      component: SaleViewComponent,
      meta: { title: i18n.tc('sale'), hideInMenu: true },
    },
    {
      name: 'views.purchase',
      path: '/views/purchase/:hash',
      component: PurchaseViewComponent,
      meta: { title: i18n.tc('purchase'), hideInMenu: true },
    },
    {
      name: 'views.payment',
      path: '/views/payment/:hash',
      component: PaymentViewComponent,
      meta: { title: i18n.tc('payment'), hideInMenu: true },
    },
    {
      name: 'views.quotation',
      path: '/views/quotation/:hash',
      component: QuotationViewComponent,
      meta: { title: i18n.tc('quotation'), hideInMenu: true },
    },
    {
      name: 'views.return_order',
      path: '/views/return_order/:hash',
      component: ReturnOrderViewComponent,
      meta: { title: i18n.tc('return_order'), hideInMenu: true },
    },
    {
      path: '*',
      name: 'error-404',
      component: Error404,
      meta: { title: i18n.t('not_found'), icon: 'md-home', hideInMenu: true },
    },
  ];
}

function builder(lang) {
  return new VueRouter({
    // mode: 'history',
    routes: allRoutesFn(lang),
    linkActiveClass: 'active',
    scrollBehavior: () => ({ y: 0 }),
  });
}

export const routes = allRoutesFn;
export default builder;
